CREATE TABLE USERS (
    ID VARCHAR2(8) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    DISPLAY_NAME VARCHAR2(255),
    CONSTRAINT USERS_ID_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_USERNAME_UN UNIQUE (USERNAME)
);
/ 

CREATE
OR REPLACE TRIGGER USERS_INSERT_TG BEFORE
INSERT
    ON USERS FOR EACH ROW DECLARE TEMP_USERID USERS.ID % TYPE;

TEMP_COUNT INT;

BEGIN
SELECT
    COUNT(*) INTO TEMP_COUNT
FROM
    USERS;

TEMP_USERID := CONCAT('USER', LPAD(TEMP_COUNT + 1, 4, '0'));

:NEW.ID := TEMP_USERID;

:NEW.USERNAME := LOWER(:NEW.USERNAME);

END;

/
INSERT INTO
    USERS (USERNAME, PASSWORD, DISPLAY_NAME)
VALUES
    ('ADMIN', 'ADMIN', 'ADMIN');

INSERT INTO
    USERS (USERNAME, PASSWORD, DISPLAY_NAME)
VALUES
    ('JOHNDOE', 'ABC123', 'JOHN DOE');

INSERT INTO
    USERS (USERNAME, PASSWORD, DISPLAY_NAME)
VALUES
    ('JANEDOE', 'P@SSW0RD', 'JANE DOE');

INSERT INTO
    USERS (USERNAME, PASSWORD, DISPLAY_NAME)
VALUES
    ('BOBSMITH', '123456', 'BOB SMITH');

INSERT INTO
    USERS (USERNAME, PASSWORD, DISPLAY_NAME)
VALUES
    ('SARAHJONES', 'QWERTY', 'SARAH JONES');

INSERT INTO
    USERS (USERNAME, PASSWORD, DISPLAY_NAME)
VALUES
    ('MIKEBROWN', 'PASS123', 'MIKE BROWN');