/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.theuntidycat.rhm.view.contract;

import com.theuntidycat.rhm.controller.ManageContractController;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class ContractUpdateDialog extends javax.swing.JFrame {

    /**
     * Creates new form ContractUpdateDialog
     */
    public ContractUpdateDialog() {
        initComponents();
        setVisible(true);
        txtRoomID.setEditable(false);
        txtRoomName.setEditable(false);
        txtRepID.setEditable(false);
        txtRepCCCD.setEditable(false);
    }
    
    public void loadRepName()
    {
        try
        {
            ManageContractController controller = new ManageContractController();
            ResultSet rs = controller.getRepCCCD(txtRepID.getText());
            rs.next();
            txtRepCCCD.setText(rs.getString(1));
        }
        catch(SQLException e)
        {
            System.out.println(e);
            System.out.println("Error in ContractUpdateDialog loadRepName");
        }
    }
    
    public void loadRoomName()
    {
        try
        {
            ManageContractController controller = new ManageContractController();
            ResultSet rs = controller.getRoomName(txtRoomID.getText());
            rs.next();
            txtRoomName.setText(rs.getString("NAME"));
        }
        catch(SQLException e)
        {
            System.out.println(e);
            System.out.println("Error in ContractUpdateDialog RoomIDAction");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonCancel = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRoomID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRoomName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRepID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRepCCCD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenantID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenantCCCD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contract Update Dialog");
        setAlwaysOnTop(true);

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonAdd.setText("Thêm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel1.setText("Mã phòng");
        jPanel2.add(jLabel1);
        jPanel2.add(txtRoomID);

        jLabel2.setText("Tên phòng");
        jPanel2.add(jLabel2);
        jPanel2.add(txtRoomName);

        jLabel3.setText("Mã người đại diện");
        jPanel2.add(jLabel3);
        jPanel2.add(txtRepID);

        jLabel4.setText("CCCD người đại diện");
        jPanel2.add(jLabel4);
        jPanel2.add(txtRepCCCD);

        jLabel5.setText("Mã người thuê muốn thêm");
        jPanel2.add(jLabel5);
        jPanel2.add(txtTenantID);

        jLabel6.setText("CCCD người thuê muốn thêm");
        jPanel2.add(jLabel6);
        jPanel2.add(txtTenantCCCD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn huỷ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION)
            setVisible(false);
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
     * @param args the command line arguments
     * @return 
     * 
     */
     
    public javax.swing.JTextField getTxtRoomID()
    {
        return txtRoomID;
    }
    public javax.swing.JTextField getRepCCCD()
    {
        return txtRepCCCD;
    }
    
    public javax.swing.JTextField getRepID()
    {
        return txtRepID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtRepCCCD;
    private javax.swing.JTextField txtRepID;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtRoomName;
    private javax.swing.JTextField txtTenantCCCD;
    private javax.swing.JTextField txtTenantID;
    // End of variables declaration//GEN-END:variables
}
