/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.theuntidycat.rhm.view.contract;

import javax.swing.table.DefaultTableModel;
import com.theuntidycat.rhm.controller.ManageContractController;
import java.sql.*;
/**
 *
 * @author Dell
 */
public class ManageContract extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ManageContract() {
        initComponents();
    }
    
    
    DefaultTableModel tblModelTT;
    public void createTable()
    {
        tblModelTT = new DefaultTableModel();
        String title[] = {"Mã HĐ", "Ngày BĐ", "Ngày KT", "Giá thuê", "Đặt cọc","Mã khách", "Mã phòng","TT phòng","TT HĐ"};
        tblModelTT.setColumnIdentifiers(title);
        try
        {
            ManageContractController controller = new ManageContractController();
            String row[] = new String[9];
            ResultSet rs = controller.getContractTable();
            while(rs.next())
            {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                row[6] = rs.getString(7);
                row[7] = rs.getString(8);
                row[8] = rs.getString(9);

                tblModelTT.addRow(row);
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            System.out.println("Error in ManageContract loadTable");
        } 
        
        tbContract.setModel(tblModelTT);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbContract = new javax.swing.JTable();
        ContractButton = new javax.swing.JPanel();
        insertNewContract = new javax.swing.JButton();
        updateContract = new javax.swing.JButton();
        viewContractDetail = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        buttonRefresh = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tbContract.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tbContract.setPreferredSize(new java.awt.Dimension(488, 335));
        jScrollPane2.setViewportView(tbContract);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        ContractButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        insertNewContract.setText("Tạo hợp đồng");
        insertNewContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertNewContractActionPerformed(evt);
            }
        });
        ContractButton.add(insertNewContract);

        updateContract.setText("Thêm người ở cùng");
        updateContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateContractActionPerformed(evt);
            }
        });
        ContractButton.add(updateContract);

        viewContractDetail.setText("Xem chi tiết");
        viewContractDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewContractDetailActionPerformed(evt);
            }
        });
        ContractButton.add(viewContractDetail);

        add(ContractButton, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel1.setText("Tìm kiếm hợp đồng");
        jPanel1.add(jLabel1);

        txtSearch.setMinimumSize(new java.awt.Dimension(150, 22));
        txtSearch.setPreferredSize(new java.awt.Dimension(200, 22));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch);

        buttonRefresh.setText("Làm mới");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRefresh);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void viewContractDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewContractDetailActionPerformed
        // TODO add your handling code here:
        int indexTB = tbContract.getSelectedRow();
        if(indexTB < tblModelTT.getRowCount() && indexTB >= 0)
        {
            ContractViewDetailDialog view = new ContractViewDetailDialog();
            view.getContractID().setText(tblModelTT.getValueAt(indexTB, 0).toString());
            view.getTxtRoomID().setText(tblModelTT.getValueAt(indexTB, 6).toString());
            view.getRepID().setText(tblModelTT.getValueAt(indexTB, 5).toString());
            view.getStartDate().setText(tblModelTT.getValueAt(indexTB, 1).toString());
            view.getEndDate().setText(tblModelTT.getValueAt(indexTB, 2).toString());
            view.getPrice().setText(tblModelTT.getValueAt(indexTB, 3).toString());
            view.getTxtStatus().setText(tblModelTT.getValueAt(indexTB, 7).toString());
            view.getDeposit().setText(tblModelTT.getValueAt(indexTB, 4).toString());
            view.loadRoomCapacity();
            view.createTable();
        }
    }//GEN-LAST:event_viewContractDetailActionPerformed

    private void insertNewContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertNewContractActionPerformed
         // TODO add your handling code here:
        ContractInsertDialog contractInsertDialog = new ContractInsertDialog();
        contractInsertDialog.setVisible(true);
    }//GEN-LAST:event_insertNewContractActionPerformed

    private void updateContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateContractActionPerformed
        // TODO add your handling code here:
        int indexTB = tbContract.getSelectedRow();
        if(indexTB < tblModelTT.getRowCount() && indexTB >= 0)
        {
            ContractUpdateDialog update = new ContractUpdateDialog();
            update.getContractID().setText(tblModelTT.getValueAt(indexTB, 0).toString());
            update.getTxtRoomID().setText(tblModelTT.getValueAt(indexTB, 6).toString());
            update.getRepID().setText(tblModelTT.getValueAt(indexTB, 5).toString());
            update.statusRoom = tblModelTT.getValueAt(indexTB, 7).toString();
            update.statusContract = tblModelTT.getValueAt(indexTB, 8).toString();
            update.loadRepName();
            update.loadRoomName();
        }
    }//GEN-LAST:event_updateContractActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        if(!"".equals(txtSearch.getText()))
        {
                try
                {
                    ManageContractController controller = new ManageContractController();
                    ResultSet rs = controller.loadNewDataContractTable(txtSearch.getText());
                    tblModelTT = new DefaultTableModel();
                    String title[] = {"Mã HĐ", "Ngày BĐ", "Ngày KT", "Giá thuê", "Đặt cọc","Mã khách", "Mã phòng","TT phòng","TT HĐ"};
                    String row[] = new String[9];
                    tblModelTT.setColumnIdentifiers(title);

                    while(rs.next())
                    {
                        row[0] = rs.getString(1);
                        row[1] = rs.getString(2);
                        row[2] = rs.getString(3);
                        row[3] = rs.getString(4);
                        row[4] = rs.getString(5);
                        row[5] = rs.getString(6);
                        row[6] = rs.getString(7);
                        row[7] = rs.getString(8);
                        row[8] = rs.getString(9);
                        tblModelTT.addRow(row);
                    }
                }
                catch(SQLException e)
                {
                    System.out.println(e);
                    System.out.println("Error in ManageContract SearchAction");
                }
                    tbContract.setModel(tblModelTT);
        }
        else
        {
            createTable();
        }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        // TODO add your handling code here:
        createTable();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    public javax.swing.JTable getTBContract()
    {
        return tbContract;
    }     
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContractButton;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton insertNewContract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbContract;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton updateContract;
    private javax.swing.JButton viewContractDetail;
    // End of variables declaration//GEN-END:variables
}
