/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.theuntidycat.rhm.view.invoice;

import com.theuntidycat.rhm.controller.ManageInvoiceController;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TTMC
 */
public class DetailInvoice extends javax.swing.JFrame {

    /**
     * Creates new form DetailInvoice
     */
    int NoCu = 0;
    public DetailInvoice() {
        initComponents();
        setVisible(true);
        createTable();
        updateDeTable();
        setLocationRelativeTo(null);
    }
    
    public void setTxt(String ph, String ky, String id){
        txtPhong.setText(ph);
        txtPhong.setEditable(false);
        txtKy.setText(ky);
        txtKy.setEditable(false);
        txtID.setText(id);
        txtID.setEditable(false);
        txtNo.setEditable(false);
        txtNo.setVisible(false);
    }
    
    public void setButton(String Status){
        if(Status.equals("Da thanh toan")){
            btSua.setVisible(false);
            btXoa.setVisible(false);
        }
    }
    
    public void setNoPaid(String Status){
        if(Status.equals("Da thanh toan")){
            NoCu = setNoInt();
            txtNo.setText("0");
        }
    }
    
    public int setNoInt(){
        String StrNo = txtNo.getText();
        int no = Integer.parseInt(StrNo);
        return no;
    }
    
    /*public void setNoUn(String StrNo){
        String StrTien = txtNo.getText();
        int No = Integer.parseInt(StrNo);
        int Tien = Integer.parseInt(StrTien);
        Tien = Tien + No;
        String str = String.valueOf(Tien);
        txtNo.setText(str);
    }*/
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbDetail = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btQL = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPhong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtKy = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNo = new javax.swing.JTextField();
        btRef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết hoá đơn");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        tbDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Loại hóa đơn", "Số lượng", "Đơn giá", "Đơn vị", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(tbDetail);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel2.add(btThem);

        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btSua);

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btXoa);

        btQL.setText("Quay lại");
        btQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLActionPerformed(evt);
            }
        });
        jPanel2.add(btQL);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel3.setText("Phòng");
        jPanel3.add(jLabel3);

        txtPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhongActionPerformed(evt);
            }
        });
        jPanel3.add(txtPhong);

        jLabel1.setText("Kỳ đóng tiền");
        jPanel3.add(jLabel1);

        txtKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKyActionPerformed(evt);
            }
        });
        jPanel3.add(txtKy);

        jLabel2.setText("Mã hóa đơn");
        jPanel3.add(jLabel2);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtID);

        txtNo.setText("0");
        jPanel3.add(txtNo);

        btRef.setText("Làm mới");
        btRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefActionPerformed(evt);
            }
        });
        jPanel3.add(btRef);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel tblModelTT;
    public void createTable()
    {
        tblModelTT = new DefaultTableModel();
        String title[] = {"Loại Hóa Đơn", "Số lượng", "Đơn giá", "Đơn vị", "Thành tiền"};
        tblModelTT.setColumnIdentifiers(title);
        tbDetail.setModel(tblModelTT);
        setVisible(true);
    }
    
    public void updateDeTable(){
        String id = txtID.getText();
        int t = 0;
        tblModelTT.setRowCount(0);
        ManageInvoiceController controller = new ManageInvoiceController();
        ResultSet rs = controller.getDetailInvoices(id);
        try{
            while(rs.next()){
                t = t + rs.getInt(5);
                Object[] arr = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getInt(5)};
                tblModelTT.addRow(arr);
            }
            t = t - NoCu;
            String StrTong = String.valueOf(t);
            txtNo.setText(StrTong);
        }catch(SQLException e){
            System.out.println("Error at ManageInvoiceController/getDetialInvoices");
        }
        
    }
    private void txtPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhongActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPhongActionPerformed

    private void txtKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtKyActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        InfDetail inf = new InfDetail(txtID.getText());
        //inf.displayID();
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(this, "Chắc chắn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if(r == JOptionPane.YES_OPTION){
            int n = tbDetail.getSelectedRow();
            String id = txtID.getText();
            String loai = (String) tbDetail.getValueAt(n, 0);
            ManageInvoiceController controller = new ManageInvoiceController();
            boolean check = controller.deleteDetailInvoice(id,loai);
            if(check){
                JOptionPane.showMessageDialog(this, "Xóa thành công", "Xác nhận", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Không thể xóa hóa đơn tồn tại chi tiết hóa đơn", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btQLActionPerformed

    private void btRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefActionPerformed
        // TODO add your handling code here:
        updateDeTable();
        if(setNoInt() > 0){
            btSua.setVisible(true);
            btXoa.setVisible(true);
        }
    }//GEN-LAST:event_btRefActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int n = tbDetail.getSelectedRow();
        String id = txtID.getText();
        String l = (String) tbDetail.getValueAt(n, 0);
        String sl = (String) tbDetail.getValueAt(n, 1);
        String dg = (String) tbDetail.getValueAt(n, 2);
        
        UpInfDetail inf = new UpInfDetail();
        inf.displayExisted(id, l, sl, dg);
    }//GEN-LAST:event_btSuaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btQL;
    private javax.swing.JButton btRef;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbDetail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKy;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtPhong;
    // End of variables declaration//GEN-END:variables

    
}
