/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.theuntidycat.rhm.view.invoice;

import com.theuntidycat.rhm.controller.ManageInvoiceController;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TTMC
 */
public class InfInvoice extends javax.swing.JFrame {

    /**
     * Creates new form InfInvoice
     */
    public InfInvoice() {
        initComponents();
        setVisible(true);
        setCbbRoom();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CbbRoom = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        CbbThang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btQuay = new javax.swing.JButton();
        btThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm hoá đơn");
        setAlwaysOnTop(true);

        jPanel1.setToolTipText("");
        jPanel1.setName("Thông tin hóa đơn"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jLabel2.setText("Tên phòng");
        jPanel2.add(jLabel2);

        jSeparator2.setForeground(java.awt.SystemColor.control);
        jSeparator2.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel2.add(jSeparator2);

        CbbRoom.setMaximumRowCount(10);
        CbbRoom.setMinimumSize(new java.awt.Dimension(80, 22));
        CbbRoom.setPreferredSize(new java.awt.Dimension(208, 22));
        CbbRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbRoomActionPerformed(evt);
            }
        });
        jPanel2.add(CbbRoom);

        jPanel1.add(jPanel2);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout2);

        jLabel3.setText("Kỳ đóng");
        jPanel3.add(jLabel3);

        jSeparator1.setForeground(java.awt.SystemColor.control);
        jSeparator1.setPreferredSize(new java.awt.Dimension(20, 10));
        jPanel3.add(jSeparator1);

        jLabel4.setText("tháng");
        jPanel3.add(jLabel4);

        CbbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        CbbThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbThangActionPerformed(evt);
            }
        });
        jPanel3.add(CbbThang);

        jLabel5.setText("năm");
        jPanel3.add(jLabel5);
        jPanel3.add(txtNam);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btQuay.setText("Quay lại");
        btQuay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuayActionPerformed(evt);
            }
        });
        jPanel4.add(btQuay);

        btThem.setText("Hoàn tất");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel4.add(btThem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setCbbRoom(){
        try{
            ManageInvoiceController controller = new ManageInvoiceController();
            ResultSet rs = controller.getRooms_Contract();
            while(rs.next()){
                CbbRoom.addItem(rs.getString(1));
            }
        } catch(SQLException e){
            System.out.println("Error at InforInvoice/setCbbRoom\nError: " + e);
        }
    }
    private void CbbThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbThangActionPerformed

    private void CbbRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbRoomActionPerformed

    private void btQuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuayActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btQuayActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        String room = CbbRoom.getItemAt(CbbRoom.getSelectedIndex());
        String month = CbbThang.getItemAt(CbbThang.getSelectedIndex());
        String year = txtNam.getText();
        
        ManageInvoiceController controller = new ManageInvoiceController();
        boolean check = controller.insertInvoice(room, month, year);
        
        if(check){
                JOptionPane.showMessageDialog(this, "Thêm thành công", "Xác nhận", JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "Trùng hóa đơn. Vui lòng nhập lại", "Xác nhận", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btThemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbRoom;
    private javax.swing.JComboBox<String> CbbThang;
    private javax.swing.JButton btQuay;
    private javax.swing.JButton btThem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtNam;
    // End of variables declaration//GEN-END:variables
}
