/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.theuntidycat.rhm.view.invoice;

import com.theuntidycat.rhm.controller.ManageInvoiceController;
import com.theuntidycat.rhm.view.utils.MessageDialog;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.sql.*;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TTMC
 */
public class ManageInvoice extends javax.swing.JPanel {

    /**
     * Creates new form ManageInvoice
     */
    //ManageInvoiceController controller = new ManageInvoiceController();
    public ManageInvoice() {
        initComponents();
        createTable();
        // updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CbbKy = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        CbbRoom = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btRef = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInvoice = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btXem = new javax.swing.JButton();

        searchPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel1.setText("Kỳ đóng:");
        searchPanel.add(jLabel1);

        CbbKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbKyActionPerformed(evt);
            }
        });
        searchPanel.add(CbbKy);

        jLabel2.setText("Phòng:");
        searchPanel.add(jLabel2);

        searchPanel.add(CbbRoom);

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        searchPanel.add(jButton1);

        btRef.setText("refresh");
        btRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefActionPerformed(evt);
            }
        });
        searchPanel.add(btRef);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(488, 285));

        tbInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa đơn", "Kỳ đóng", "Phòng", "Tổng tiền", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tbInvoice);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btXem.setText("Xem chi tiết");
        btXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59)
                .addComponent(btThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btXem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(91, 91, 91))
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThem)
                    .addComponent(btSua)
                    .addComponent(btXoa)
                    .addComponent(btXem))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setCbbRoom() {
        try {
            ManageInvoiceController controller = new ManageInvoiceController();
            CbbRoom.removeAllItems();
            CbbRoom.addItem("Tất cả");
            ResultSet rs = controller.getRooms();
            while (rs.next()) {
                CbbRoom.addItem(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println("Error at ManageInvoice/setCbbRoom\nError: " + e);
        }
    }

    public void setCbbPeriod() {
        try {
            ManageInvoiceController controller = new ManageInvoiceController();
            CbbKy.removeAllItems();
            CbbKy.addItem("Tất cả");
            ResultSet rs = controller.getPeriod();
            while (rs.next()) {
                CbbKy.addItem(rs.getString(1));
            }
        } catch (SQLException e) {
            System.out.println("Error at ManageInvoice/setCbbPeriod\nError: " + e);
        }
    }

    DefaultTableModel tblModelTT;

    public void createTable() {
        tblModelTT = new DefaultTableModel();
        String title[] = {"Mã Hóa Đơn", "Kỳ đóng", "Phòng", "Tổng tiền", "Trạng thái", "Còn nợ"};
        tblModelTT.setColumnIdentifiers(title);
        tbInvoice.setModel(tblModelTT);
        setVisible(true);
    }

    public void updateTable() {
        setCbbRoom();
        setCbbPeriod();
        int Money_unpaid;
        try {
            ManageInvoiceController controller = new ManageInvoiceController();
            ResultSet rs = controller.getInvoices();
            tblModelTT.setRowCount(0);
            while (rs.next()) {
                Money_unpaid = rs.getInt(4) - rs.getInt(6);
                String unpaid = String.valueOf(Money_unpaid);
                String arr[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), unpaid};
                tblModelTT.addRow(arr);
            }
        } catch (SQLException e) {
            System.out.println("Error at ManageInvoice/updateTable");
        }
    }

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        InfInvoice inf = new InfInvoice();
        
    }//GEN-LAST:event_btThemActionPerformed

    private void btXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemActionPerformed
        // TODO add your handling code here:
        int n = tbInvoice.getSelectedRow();

        String Status = (String) tbInvoice.getValueAt(n, 4);
        String ph = (String) tbInvoice.getValueAt(n, 2);
        String k = (String) tbInvoice.getValueAt(n, 1);
        String id = (String) tbInvoice.getValueAt(n, 0);

        DetailInvoice detail = new DetailInvoice();
        detail.setTxt(ph, k, id);
        detail.updateDeTable();
        detail.setNoPaid(Status);
        detail.setButton(Status);
    }//GEN-LAST:event_btXemActionPerformed

    private void CbbKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbKyActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        MessageDialog confirmDialog = new MessageDialog(this, "Xác nhận", "Xác nhận xoá?", JOptionPane.QUESTION_MESSAGE, JOptionPane.YES_NO_OPTION);
        confirmDialog.setVisible(true);
        int selection = confirmDialog.getSelection();
        if (selection == JOptionPane.YES_OPTION) {
            int n = tbInvoice.getSelectedRow();
            String id = (String) tbInvoice.getValueAt(n, 0);
            ManageInvoiceController controller = new ManageInvoiceController();
            boolean check = controller.deleteInvoice(id);
            if (check) {
                JOptionPane.showMessageDialog(this, "Xoá thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Xoá thất bại");
            }
        }
        //else{

        //}
    }//GEN-LAST:event_btXoaActionPerformed

    private void btRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefActionPerformed
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_btRefActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int n = tbInvoice.getSelectedRow();
        String status = (String) tbInvoice.getValueAt(n, 4);
        String Str_tong = (String) tbInvoice.getValueAt(n, 3);
        int tong = Integer.parseInt(Str_tong);
        String ph = (String) tbInvoice.getValueAt(n, 2);
        String k = (String) tbInvoice.getValueAt(n, 1);
        String[] ky = k.split("/");
        String id = (String) tbInvoice.getValueAt(n, 0);

        if (status.equals("Da thanh toan")) {
            JOptionPane.showMessageDialog(this, "Không thể sửa hóa đơn đã thanh toán", "Xác nhận", JOptionPane.INFORMATION_MESSAGE);
        } else if (tong > 0) {
            updateInfInvoice inf = new updateInfInvoice();
            inf.displayEditable(ph, ky[0], ky[1], id, status);
        } else {
            updateInfInvoice inf = new updateInfInvoice();
            inf.displayExisted(ph, ky[0], ky[1], id, status);
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String room = CbbRoom.getItemAt(CbbRoom.getSelectedIndex());
        String k = CbbKy.getItemAt(CbbKy.getSelectedIndex());
        String[] ky;
        if (!k.equals("Tất cả")) {
            ky = k.split("/");
        }
        try {
            if (room.equals("Tất cả") && k.equals("Tất cả")) {
                tblModelTT.setRowCount(0);
                updateTable();
            } else {
                ManageInvoiceController controller = new ManageInvoiceController();
                ResultSet rs = controller.filterInvoices(room, k);
                tblModelTT.setRowCount(0);
                while (rs.next()) {
                    String arr[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                    tblModelTT.addRow(arr);
                }
                setVisible(true);
            }
        } catch (SQLException e) {
            System.out.println("Error at ManageInvoice/searchInvoice");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbKy;
    private javax.swing.JComboBox<String> CbbRoom;
    private javax.swing.JButton btRef;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXem;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable tbInvoice;
    // End of variables declaration//GEN-END:variables

}
