/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.theuntidycat.rhm.view.invoice;

import com.theuntidycat.rhm.controller.ManageInvoiceController;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author TTMC
 */
public class updateInfInvoice extends javax.swing.JFrame {

    /**
     * Creates new form updateInfInvoice
     */
    public updateInfInvoice() {
        initComponents();
        setVisible(true);
        setCbbRoom();
        setLocationRelativeTo(null);
    }
    
    public void displayExisted(String room, String month, String year, String id, String Status){
        CbbRoom.setSelectedItem(room);
        CbbThang.setSelectedItem(month);
        txtNam.setText(year);
        txtID.setText(id);
        txtID.setEditable(false);
        CbbS.setSelectedItem(Status);
    }
    
    public void displayEditable(String room, String month, String year, String id, String Status){
        CbbRoom.setSelectedItem(room);
        CbbRoom.setEnabled(false);
        CbbThang.setSelectedItem(month);
        CbbThang.setEnabled(false);
        txtNam.setText(year);
        txtNam.setEditable(false);
        txtID.setText(id);
        txtID.setEditable(false);
        CbbS.setSelectedItem(Status);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CbbThang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        CbbRoom = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        CbbS = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        btQuay = new javax.swing.JButton();
        btThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập nhật HĐ");
        setAlwaysOnTop(true);
        setPreferredSize(null);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(null);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jLabel4.setText("Tháng");
        jPanel2.add(jLabel4);

        jSeparator1.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator1.setPreferredSize(new java.awt.Dimension(30, 10));
        jPanel2.add(jSeparator1);

        CbbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        CbbThang.setPreferredSize(new java.awt.Dimension(50, 22));
        CbbThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbThangActionPerformed(evt);
            }
        });
        jPanel2.add(CbbThang);

        jLabel5.setText("Năm");
        jPanel2.add(jLabel5);
        jPanel2.add(txtNam);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(70, 90));
        jPanel4.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        jLabel2.setText("Tên phòng");
        jPanel4.add(jLabel2);

        jLabel1.setText("Mã hóa đơn");
        jPanel4.add(jLabel1);

        jLabel3.setText("Trạng thái");
        jPanel4.add(jLabel3);

        jPanel3.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(150, 90));
        jPanel5.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        CbbRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbRoomActionPerformed(evt);
            }
        });
        jPanel5.add(CbbRoom);
        jPanel5.add(txtID);

        CbbS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Da thanh toan", "Chua thanh toan" }));
        jPanel5.add(CbbS);

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btQuay.setText("Quay lại");
        btQuay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuayActionPerformed(evt);
            }
        });
        jPanel6.add(btQuay);

        btThem.setText("Hoàn tất");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel6.add(btThem);

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setCbbRoom(){
        try{
            ManageInvoiceController controller = new ManageInvoiceController();
            ResultSet rs = controller.getRooms_Contract();
            while(rs.next()){
                CbbRoom.addItem(rs.getString(1));
            }
        } catch(SQLException e){
            System.out.println("Error at InforInvoice/setCbbRoom\nError: " + e);
        }
    }
    private void btQuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuayActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btQuayActionPerformed

    private void CbbRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbRoomActionPerformed

    private void CbbThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbThangActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        String room = CbbRoom.getItemAt(CbbRoom.getSelectedIndex());
        String month = CbbThang.getItemAt(CbbThang.getSelectedIndex());
        String year = txtNam.getText();
        String Status = CbbS.getItemAt(CbbS.getSelectedIndex());
        String id = txtID.getText();
        String S_id = null;
        if(Status.equals("Chưa thanh toán")){
            S_id = "0";
        } else {
            S_id = "1";
        }
        
        ManageInvoiceController controller = new ManageInvoiceController();
        boolean check = controller.updateInvoice(room, month, year, id, S_id);
        
        if(check){
            JOptionPane.showMessageDialog(null, "Sửa thành công", "Xác nhận", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập lại", "Xác nhận", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btThemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbRoom;
    private javax.swing.JComboBox<String> CbbS;
    private javax.swing.JComboBox<String> CbbThang;
    private javax.swing.JButton btQuay;
    private javax.swing.JButton btThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNam;
    // End of variables declaration//GEN-END:variables
}
